technical_researcher:
  tools:
  - simple_research_tool
  - read_excel_file
  description: Ferramentas para pesquisa e coleta de informações.
data_analyst:
  tools:
  - analyze_excel_similarity
  - detect_data_patterns
  - generate_excel_report
  description: Ferramentas para análise avançada e geração de relatórios.
technical_writer:
  tools:
  - generate_excel_report
  description: Ferramentas para geração e formatação de conteúdo técnico.
technical_reviewer:
  tools:
  - validate_excel_file
  - detect_data_patterns
  description: Ferramentas para validação, revisão de dados e conformidade.
technical_coordinator:
  tools:
  - read_excel_file
  - execution_summary_builder
  description: Ferramentas para coordenação e sumarização.
crewai_evaluator:
  tools:
  - crew_performance_analyzer
  - agent_output_quality_checker
  - tool_usage_evaluator
  - workflow_efficiency_analyzer
  - recommendation_generator
  - execution_summary_builder
  description: Ferramentas especializadas para avaliação abrangente de crews.
simple_evaluator:
  tools:
  - crew_performance_analyzer
  - execution_summary_builder
  description: Ferramentas básicas para avaliação de fallback.
